version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
