# Build the app
FROM node:20.11.1-alpine AS build

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Run the builded app
FROM nginx:1.24-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./prod/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
