version: "3.8"
services:
  app:
    image: node:alpine
    entrypoint: /bin/sh
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true

#version: "3.8"
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile

